### QueueTixException 처리 테스트
GET http://localhost:8080/test/queue-tix
Accept: application/json
### IllegalArgumentException 처리 테스트
GET http://localhost:8080/test/illlegal-argument
Accept: application/json
### serverError 처리 테스트
GET http://localhost:8080/test/server-error
Accept: application/json
### validation Error 처리 테스트
GET http://localhost:8080/test/validation
Accept: application/json
Content-Type: application/json

{
  "loginId": "test"
}